todo/urls.py
from django.urls import path
from .views import (
    TaskView,
    TagView,
    TaskCreateView,
    TaskDeleteView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
    TaskUpdateView,
    toggle_complete
)

urlpatterns = [
    path("", TaskView.as_view(), name="task_list"),

    path("tags/", TagView.as_view(), name="tag_list"),
    path("tag/create/", TagCreateView.as_view(), name="tag_create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),

    path("create/", TaskCreateView.as_view(), name="task_create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task_update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),

    path("<int:pk>/toggle/", toggle_complete, name="task_toggle"),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(null=True)
    tags = models.ManyToManyField(Tag, related_name="tasks")
    complete = models.BooleanField(default=False, blank=True)

    class Meta:
        ordering = ("complete", "-date")

    def __str__(self):
        return f"{self.title} {self.date} {self.deadline} {self.tags}"

todo/forms.py
from django import forms
from django.forms import ModelForm

from .models import Task


class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = ("title", "deadline", "tags")
        widgets = {
            'deadline': DateTimeInput(),
        }

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Task, Tag


class TaskView(generic.ListView):
    model = Task
    template_name = "todo/todo_list.html"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/todo_form.html"
    success_url = reverse_lazy("todo:task_list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/todo_form.html"
    success_url = reverse_lazy("todo:task_list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo/todo_delete.html"
    success_url = reverse_lazy("todo:task_list")


class TagView(generic.ListView):
    model = Tag
    template_name = "tag/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "tag/tag_form.html"
    success_url = reverse_lazy("todo:tag_list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "tag/tag_form.html"
    success_url = reverse_lazy("todo:tag_list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "tag/tag_delete.html"
    success_url = reverse_lazy("todo:tag_list")


def toggle_complete(request, pk):
    task = Task.objects.get(id=pk)
    task.complete = not task.complete
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task_list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>
    {% block title %}
      ToDo list
    {% endblock %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
</head>
<body>
  <div class="row" style="margin-top: 30px">

    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/navbar.html" %}
      {% endblock %}
    </div>

    <div class="col-sm-8 ">
      {% block content %}{% endblock %}
    </div>

  </div>
</body>

</html>

templates/includes/navbar.html
<ul>
  <li class="list-group-item">
    <a href="{% url 'todo:task_list' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'todo:tag_list' %}">Tag List</a>
  </li>
</ul>

templates/tag/tag_delete.html
{% extends "base.html" %}

{% block content %}

  <h4>Are you sure you want to delete the tag?</h4>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>

{% endblock %}

templates/tag/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1 style="margin-top: 5px">
    {{ object|yesno:"Update,Create" }} Tags
  </h1>

  <form action="" method="post" style="max-width: 400px;">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" style="margin-top: 20px" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/tag/tag_list.html
{% extends "base.html" %}

{% block content %}

  <h1>
    Tag list
  </h1>
  <a href="{% url 'todo:tag_create' %}" class="btn btn-primary link-to-page">
    Add Tag
  </a>

  {% if tag_list %}

    <table class="table" style="margin-top: 20px">
      <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
      </thead>

      <tbody>
      {% for tag in  tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a class="btn btn-success link-to-page" href="{% url 'todo:tag_update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a class="btn btn-danger link-to-page" href="{% url 'todo:tag_delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
        </tbody>
      {% endfor %}
    </table>

  {% else %}
    <h4>Tag list is empty!</h4>
  {% endif %}

{% endblock %}

templates/todo/todo_delete.html
{% extends "base.html" %}

{% block content %}

  <h4>Are you sure you want to delete the task?</h4>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>

{% endblock %}

templates/todo/todo_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 style="margin-top: 5px">
    {{ object|yesno:"Update,Create" }} Task
  </h1>

  <form action="" method="post" style="max-width: 400px;">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/todo/todo_list.html
{% extends "base.html" %}

{% block content %}

  <h1>
    TODO list
  </h1>
  <a href="{% url 'todo:task_create' %}" class="btn btn-primary link-to-page" style="margin-bottom: 20px">
    Add Task
  </a>

  {% if task_list %}
    {% for task in task_list %}

      <div style="border: solid #5b5b5b; margin-bottom: 10px; padding: 40px" class="rounded">

        {% if  task.complete %}
          <h2>
            {{ task.name }}
            <a style="float: right" href="{% url 'todo:task_toggle' pk=task.id %}"
               class="btn btn-secondary link-to-page">
              Undo
            </a>
          </h2>
        {% else %}
          <h2>
            {{ task.name }}
            <a style="float: right" href="{% url 'todo:task_toggle' pk=task.id %}"
               class="btn btn-success link-to-page">
              Complete
            </a>
          </h2>
        {% endif %}

        <div style="display: flex">
          <h2>
            {{ task.title }}
          </h2>
          {% if  task.complete %}
            <h5 style="color: #7de87d">Done</h5>
          {% else %}
            <h5 style="color: #c92525">Not Done</h5>
            {% if task.date > task.deadline %}
              <h5 style="color: #c92525; margin-left: 10px;">The time is up.</h5>
            {% endif %}
          {% endif %}
        </div>

        <div style="display: flex;">
          <p>Create: {{ task.date }}</p>
          <p style="color: #7a3333; margin-left: 10px">Deadline: {{ task.deadline }}</p>
        </div>

        <div style="display: flex;">
          <p>Tags:
            {% for tag in task.tags.all %}
              {{ tag.name }}
            {% endfor %}
          </p>

          <a href="{% url 'todo:task_update' pk=task.id %}" style="margin-left: 10px">Update</a>
          <a href="{% url 'todo:task_delete'  pk=task.id %}" style="margin-left: 10px">Delete</a>
        </div>
      </div>

    {% endfor %}
  {% else %}
    <h4>Todo list is empty</h4>
  {% endif %}

{% endblock %}